---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      box: mj-ubuntu14
      box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[mj-users::default]
    attributes:
      mj-users:
        work_user: mj
        bashrc_common_users:
          - maji
